import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import './globals.css'
import Navbar from '@/component/navbar';
import Footer from '@/component/footer';
import { Box } from "@mui/material";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Navbar />
          <Box minHeight={'90vh'} display={'flex'} flexDirection={'column'} >
            {children}
          </Box>
          <Box>

            <Footer />
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
